#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Judy
Version  : 1.0.5
Release  : 1
URL      : https://downloads.sourceforge.net/project/judy/judy/Judy-1.0.5/Judy-1.0.5.tar.gz
Source0  : https://downloads.sourceforge.net/project/judy/judy/Judy-1.0.5/Judy-1.0.5.tar.gz
Summary  : C library creating and accessing dynamic arrays
Group    : Development/Tools
License  : LGPL-2.1
Requires: Judy-lib = %{version}-%{release}
Requires: Judy-license = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : gfortran
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
Patch1: nodocs.patch

%description
Judy - C library creating and accessing dynamic arrays
==============================================================

%package dev
Summary: dev components for the Judy package.
Group: Development
Requires: Judy-lib = %{version}-%{release}
Provides: Judy-devel = %{version}-%{release}
Requires: Judy = %{version}-%{release}
Requires: Judy = %{version}-%{release}

%description dev
dev components for the Judy package.


%package lib
Summary: lib components for the Judy package.
Group: Libraries
Requires: Judy-license = %{version}-%{release}

%description lib
lib components for the Judy package.


%package license
Summary: license components for the Judy package.
Group: Default

%description license
license components for the Judy package.


%prep
%setup -q -n judy-1.0.5
cd %{_builddir}/judy-1.0.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582128296
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1582128296
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Judy
cp %{_builddir}/judy-1.0.5/COPYING %{buildroot}/usr/share/package-licenses/Judy/4d8c956417d05a2b99d8d4167c4bdf99cdd52f11
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/Judy.h
/usr/lib64/libJudy.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libJudy.so.1
/usr/lib64/libJudy.so.1.0.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Judy/4d8c956417d05a2b99d8d4167c4bdf99cdd52f11
